spring:
  application:
    name: Trusty Audit Paperless System

#  datasource:
#    # URL dinâmica: se não definir DATASOURCE_URL, usa H2 em memória
#    url: jdbc:h2:mem:trustydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#    hikari:
#      maximum-pool-size: 5
#      minimum-idle: 2
#      idle-timeout: 30000
#      max-lifetime: 1800000
#      leak-detection-threshold: 10000

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  flyway:
#    enabled: false
#    locations: classpath:db/migration
#    schemas: trusty

server:
  address: 0.0.0.0
##  port: ${PORT:8080}
#  servlet:
#    context-path: /api

jwt:
  secret: ${JWT_SECRET}
  token:
    expiration:  86400000 # 1 dia

frontend:
  url: ${FRONTEND_URL}