spring:
  application:
    name: Trusty Audit Paperless System

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/trusty}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 10000
      max-lifetime: 20000
      leak-detection-threshold: 10000

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  flyway:
    enabled: false
    locations: classpath:db/migration
    schemas: trusty

server:
  address: 0.0.0.0
##  port: ${PORT:8080}
#  servlet:
#    context-path: /api

jwt:
  secret: ${JWT_SECRET}
  token:
    expiration:  86400000 # 1 dia

frontend:
  url: ${FRONTEND_URL}